### ISSUE TITLE
[raygui] Possible to use raygui in current stable or (4.2)?

### ISSUE THREAD

**Issue by Shpendicus** [ChrisDill/Raylib-cs#130]
Before submitting a new issue, please verify and check:

 - [ y ] The issue is specific to Raylib-cs and not raylib
 - [ y ] I checked there is no similar issue already reported
 - [ y ] My code has no errors or misuse of Raylib-cs

### Issue description

*Import raygui so one can deal with extra windows which right now is not allowed /possible through raylib.h*

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU, Raylib-cs version, Raylib version (if applicable), and details of where or how you experienced the issue.*

* MacBook Pro 2012
* Macosx Catalina 10.15.7 
* Raylib-cs 4.0.2

Best regards

**Comment by jasonswearingen** [comment]
raygui is removed from raylib 4.2, and is now a stand-alone library.    Raylib-Cs explicitly tracks raylib, so I think they are removing raygui support.    If you need Raygui, you can use Raylib-cslo, which tries to include all the raylib extras possible.

**Comment by ChrisDill** [comment]
To clarify the position on extras. Raylib-cs is focused on the main raylib api. I tried to support extras like raygui/physac but decided to remove them to keep the library easier to maintain and allow the user to add the extras they want separately.

While a custom build can include the extras, I found that these type of extras make more sense as separate libraries, rather than any single approach being tied to Raylib-cs. For example, you could use [rlImgui-cs](https://github.com/raylib-extras/rlImGui-cs) without having 2 ui libraries in the same project.

I also think these extras might benefit more from a direct port instead of bindings as it removes the need for separate native builds though I have not tried this myself.
