### ISSUE TITLE
Wpf integration 

### ISSUE THREAD

**Issue by zs-3** [chrisdill/raylib-cs#271]
Could anyone tell how I can integrate Raylib in WPF through its handle.
I am using Raylib-cs 3.0 version.

**Comment by TacoGuyAT** [comment]
I was looking towards this thing too, I've tried embedding it using [HwndHost](https://learn.microsoft.com/en-us/dotnet/api/system.windows.interop.hwndhost?view=windowsdesktop-8.0) previously, but it's a really hacky and shaky way which causes some syncing issues, especially when resizing an app.

The only thing I can suggest is creating a separate WPF control, rendering to RenderTexture, drawing it in app using WPF API and rerouting inputs to Raylib. It's still hacky, adds overhead, but that's a constant issue when dealing with both DirectX & OpenGL at the same time.

I also thought of custom [platform](https://github.com/raysan5/raylib/tree/master/src/platforms) initially, but it would only make less mess if you implement DirectX rendering ([or use a fork which implements it](https://www.reddit.com/r/raylib/comments/1ey6pfi/directx_12_support/)), otherwise, you'll still have the same messy rendering scheme as described previously. And you'd have to make changes to Raylib itself, which is past the C# at this point.

IMO, this looks like an out of scope issue to be resolved by another library rather than wrapper itself, especially due to WPF being a Windows-only framework.
