### ISSUE TITLE
GetImageData as Color[]

### ISSUE THREAD

**Issue by horseyhorsey** [ChrisDill/Raylib-cs#53]
Hi 

I've been attempting to get a `Color[]` from the screen but not sure how to get the array of pixels from the `ToPointer`,  just returns a single `Color` ?

```            
var img = Raylib.GetScreenData();
var img2 = Raylib.GetImageData(img);
Color* mapPixels = (Color*)img2.ToPointer();
```

**Comment by ChrisDill** [comment]
It shows a single element because mapPixels is a pointer and it shows shows the element it is pointing to. This does not mean there is only one element inside it.

You can see this by looping through the colors. Note there is a large number of colors in screendata.
```csharp
unsafe
{
    var img = Raylib.GetScreenData();
    var img2 = Raylib.GetImageData(img);
    Color* mapPixels = (Color*)img2.ToPointer();

    for (int i = 0; i < img.width * img.height; i += 1)
    {
        Color color = mapPixels[i];
        // Use color here
    }
```

You could also use the newer [Span<T>](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-3.1) which may be more suitable for your needs.
```csharp
unsafe
{
    var img = Raylib.GetScreenData();
    var img2 = Raylib.GetImageData(img);

    Span<Color> colors = new Span<Color>(img2.ToPointer(), img.width * img.height);
    foreach (var color in colors)
    {
        // Use color here
    }
}
```

**Comment by horseyhorsey** [comment]
Thanks. I wasn't aware of Span or the `Color*` asterix reference in C#. That should've rang bells from using C.

`Note there is a large number of colors in screendata.`

Yes, I do have a small display though which may help it get through the work! :)
