### ISSUE TITLE
Android / Xamarin Platform Support

### ISSUE THREAD

**Issue by ejamshidiasl** [ChrisDill/Raylib-cs#87]
is there any way to use with xamarin? (run on android)

**Comment by EralpCelebi** [comment]
Definitely not qualified for this but [this ](https://docs.microsoft.com/tr-tr/dotnet/api/xamarin.forms.openglview?view=xamarin-forms) might be useful.

I personally don't think Xamarin is the right way to go with this, you might have better luck porting your code over to C++ if the challenge is not too great :)

**Comment by anggape** [comment]
i already made raylib-cs run on android on [this](https://github.com/anggape/Raylib-cs) repo
but i think we need a custom build of [this line](https://github.com/raysan5/raylib/blob/e87caa268784e8947f76bf3f6b45699553337709/src/rcore.c#L698) on raylib source

**Comment by lorenzo774** [comment]
@anggape Hi, can you write a guide on how to set up raylib-cs to run on Android?

**Comment by anggape** [comment]
also you need to instal android workload documented [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install)

**Comment by anggape** [comment]
sorry for slow response, i think i accidentally deleted the previous implementation while ago, but i reimplement it again here https://github.com/anggape/Raylib-cs/tree/android

**Comment by sdb7** [comment]
Hi, i am trying to use raylib-cs.Android by project files and by assembly still unable to run it because of this unhandled exception

![image](https://github.com/ChrisDill/Raylib-cs/assets/6058513/c8c30246-57bb-487d-91e7-341a7d0dcddf)

is there any step i am missing or dll that need to be include?

my current project setup is android app using net core 6 and 7 via visual studio project template.

**Comment by anggape** [comment]
@sdb7 if you use `Raylib-cs.Native` from master branch it does not include android native libraries until #186 finished, you need to manualy download `Raylib-cs.Native.[SOME_VERSION].nupkg` from github artifacts, use https://github.com/anggape/raylib-cs-samples if you want to try, and please give feedback since its an experimental

**Comment by ChrisDill** [comment]
Decided to change Raylib-cs.Android to Examples.Android. Easier to maintain as an example rather than a package. @anggape Could use help getting it to work the same as your samples project.

**Comment by ChrisDill** [comment]
Closing in favour of using #144 to track platform support instead.
